Updating ingress scrape config to remove fixed  pod name
nginxinc/nginx-service-mesh pull request #97
Opened 2022-12-19 20:30 UTC by chase-kiefer

### Proposed changes
Currently, the scrape config only targets pods with the name nginx-plus-ingress. This causes a failure to scrape when deploying ingress with helm, due to the release name being concatenated onto the pod name.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-service-mesh/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2022-12-19 20:45 UTC, sjberman requested changes

2022-12-19 20:45 UTC, sjberman commented on examples/nginx-plus-ingress-scrape-config.yaml
> +    - source_labels: [__meta_kubernetes_pod_annotation_nsm_nginx_com_enable_ingress]
We also have an "enable egress" annotation, we'll need to cover both cases.

2022-12-20 20:49 UTC, jbyers19 approved these changes
LGTM

2022-12-20 20:56 UTC, avahahn approved these changes

2022-12-21 15:54 UTC, sjberman approved these changes

2022-12-21 16:31 UTC, merged